### ISSUE TITLE
Undeclared variable noAPIToken

### ISSUE THREAD

**Issue by lwo** [IQSS/TwoRavens#42]
The undeclared noAPIToken variable breaks it for me:
https://github.com/IQSS/TwoRavens/blob/master/rook/rookdata.R#L66

The log shows a: "simpleError in identical(dataurl, noAPIToken): object 'noAPIToken' not found"

**Comment by tercer** [comment]
Should be corrected now.

**Comment by tercer** [comment]
The changes are up and working on https://dataverse-demo.iq.harvard.edu
