### ISSUE TITLE
Soon, update dataverse-demo.iq.harvard.edu to demo.dataverse.org

### ISSUE THREAD

**Issue by pdurbin** [IQSS/TwoRavens#47]
I'm working on renaming dataverse-demo.iq.harvard.edu to demo.dataverse.org in https://github.com/IQSS/dataverse/issues/2651 and I noticed several references to the former hostname in this repo:

https://github.com/IQSS/TwoRavens/search?utf8=%E2%9C%93&q=dataverse-demo

I'm opening this issue to get the discussion rolling on what if anything should be updated in this repo after I flip the switch.

**Comment by tercer** [comment]
Made changes to the development branch to point to beta.dataverse.org which is where development runs.  Development will move to master shortly enough.
